[["Chapter 7"]]
doi = "10.1002/tera.1420500105"
number = 13
name = "1. McKeigue PM, Lamm SH, Linn S, Kutcher JS. Bendectin and birth defects: I. A meta-analysis of the epidemiologic studies. Teratology. 1994;50(1):27–37. doi:10.1002/tera.1420500105."

[["Chapter 8"]]
doi = "10.1146/annurev-med-091014-115715"
number = 3
name = "1. Wong FCK, Lo YMD. Prenatal Diagnosis Innovation: Genome Sequencing of Maternal Plasma. Annual Review of Medicine. 2016;67(1):419–432. doi:10.1146/annurev-med-091014-115715."

[["Chapter 8"]]
doi = "10.1016/S0140-6736(97)02449-5"
number = 10
name = "1. Sundberg K, Bang J, Smidt-Jensen S, et al. Randomised study of risk of fetal loss related to early amniocentesis versus chorionic villus sampling. The Lancet. 1997;350(9079):697–703. doi:10.1016/s0140-6736(97)02449-5."

