[["Chapter 7"]]
doi = "10.1002/tera.1420500105"
number = 13
name = "McKeigue, P. M., Lamm, S. H., Linn, S., & Kutcher, J. S. (1994). Bendectin and birth defects: I. A meta-analysis of the epidemiologic studies. Teratology, 50, 27–37."

[["Chapter 8"]]
isbn = "9780443069307"
number = 1
name = "Steven G. Gabbe, Jennifer R. Niebyl, and Joe Leigh Simpson, _Obstetrics: Normal and Problem Pregnancies_ (Churchill Livingstone, 2007)"

[["Chapter 8"]]
doi = "10.1146/annurev-med-091014-115715"
number = 3
name = "Wong, F. C. K., & Lo, Y. M. D. (2016). Prenatal Diagnosis Innovation: Genome Sequencing of Maternal Plasma. Annual Review of Medicine, 67, 419–432."

[["Chapter 8"]]
doi = "10.1002/uog.14792"
number = 4
name = "Zhang, H., Gao, Y., Jiang, F., Fu, M., Yuan, Y., Guo, Y., … Wang, W. (2015). Non-invasive prenatal testing for trisomies 21, 18 and 13: clinical experience from 146 958 pregnancies. Ultrasound in Obstetrics & Gynecology, 45, 530–538."

[["Chapter 8"]]
doi = "10.1097/GIM.0b013e3182368a0e"
number = 5
name = "Palomaki, G. E., Kloza, E. M., Lambert-Messerlian, G. M., Haddow, J. E., Neveux, L. M., Ehrich, M., … Canick, J. A. (2011). DNA sequencing of maternal plasma to detect Down syndrome: An international clinical validation study. Genetics in Medicine, 13, 913–920."

[["Chapter 8"]]
doi = "10.1056/NEJMoa043693"
number = 6
name = "Malone, F. D., Canick, J. A., Ball, R. H., Nyberg, D. A., Comstock, C. H., Bukowski, R., … D’Alton, M. E. (2005). First-Trimester or Second-Trimester Screening, or Both, for Down’s Syndrome. New England Journal of Medicine, 353, 2001–2011."

[["Chapter 8"]]
doi = "10.1002/uog.5331"
number = 7
name = "Kagan, K. O., Wright, D., Baker, A., Sahota, D., & Nicolaides, K. H. (2008). Screening for trisomy 21 by maternal age, fetal nuchal translucency thickness, free beta-human chorionic gonadotropin and pregnancy-associated plasma protein-A. Ultrasound in Obstetrics and Gynecology, 31, 618–624."

[["Chapter 8"]]
doi = "10.1056/NEJMoa043693"
number = 8
name = "Malone, F. D., Canick, J. A., Ball, R. H., Nyberg, D. A., Comstock, C. H., Bukowski, R., … D’Alton, M. E. (2005). First-Trimester or Second-Trimester Screening, or Both, for Down’s Syndrome. New England Journal of Medicine, 353, 2001–2011."

[["Chapter 8"]]
doi = "10.1002/pd.420"
number = 9
name = "Spencer, K., & Nicolaides, K. H. (2002). A first trimester trisomy 13/trisomy 18 risk algorithm combining fetal nuchal translucency thickness, maternal serum free\u202f?-hCG and PAPP-A. Prenatal Diagnosis, 22, 877–879."

[["Chapter 8"]]
doi = "10.1016/S0140-6736(97)02449-5"
number = 10
name = "Sundberg, K., Bang, J., Smidt-Jensen, S., Brocks, V., Lundsteen, C., Parner, J., … Philip, J. (1997). Randomised study of risk of fetal loss related to early amniocentesis versus chorionic villus sampling. The Lancet, 350, 697–703."

[["Chapter 8"]]
doi = "10.1016/S0140-6736(86)91218-3"
number = 12

[["Chapter 8"]]
doi = "10.1097/01.AOG.0000240135.13594.07"
number = 13

[["Chapter 8"]]
doi = "10.1097/AOG.0b013e318162eb53"
number = 14

[["Chapter 8"]]
doi = "10.1097/01.AOG.0000232512.46869.fc"
number = 15

[["Chapter 8"]]
doi = "10.1002/14651858.CD003252"
number = 16

[["Chapter 8"]]
doi = "10.1097/AOG.0b013e3181875b92"
number = 17


[["Chapter 8"]]
doi = "10.1016/j.ajog.2008.12.027"
number = 18




[["Chapter 11"]]
doi = "10.1159/000089065"
number = 1
name = "McKenna, D. S., Ventolini, G., Neiger, R., & Downing, C. (2005). Gender-Related Differences in Fetal Heart Rate during First Trimester. Fetal Diagnosis and Therapy, 21, 144–147."

[["Chapter 11"]]
doi = "10.1097/AOG.0b013e3181c3c938"
number = 2
name = "Scheffer, P. G., van der Schoot, C. E., Page-Christiaens, G. C. M. L., Bossers, B., van Erp, F., & de Haas, M. (2010). Reliability of Fetal Sex Determination Using Maternal Plasma. Obstetrics & Gynecology, 115, 117–126."

[["Chapter 11"]]
doi = "10.1111/j.0730-7659.2004.00319.x"
number = 3
name = "Shipp, T. D., Shipp, D. Z., Bromley, B., Sheahan, R., Cohen, A., Lieberman, E., & Benacerraf, B. (2004). What Factors Are Associated with Parents’ Desire To Know the Sex of Their Unborn Child? Birth, 31, 272–279."

[["Chapter 11"]]
doi = "10.1056/NEJM199512073332301"
number = 4
name = "Wilcox, A. J., Weinberg, C. R., & Baird, D. D. (1995). Timing of Sexual Intercourse in Relation to Ovulation — Effects on the Probability of Conception, Survival of the Pregnancy, and Sex of the Baby. New England Journal of Medicine, 333, 1517–1521."

[["Chapter 13"]]
doi = "10.1016/j.placenta.2005.09.001"
number = 1
name = "GEDEON, C., & KOREN, G. (2006). Designing Pregnancy Centered Medications: Drugs Which Do Not Cross the Human Placenta☆. Placenta, 27, 861–868."

[["Chapter 14"]]
doi = "10.1016/j.jpeds.2010.12.055"
number = 2
name = "Potharst, E. S., van Wassenaer, A. G., Houtzager, B. A., van Hus, J. W. P., Last, B. F., & Kok, J. H. (2011). High Incidence of Multi-Domain Disabilities in Very Preterm Children at Five Years of Age. The Journal of Pediatrics, 159, 79–85."

[["Chapter 14"]]
doi = "10.1542/peds.2008-2315"
number = "3a"
name = "Van Baar, A. L., Vermaas, J., Knots, E., de Kleine, M. J. K., & Soons, P. (2009). Functioning at School Age of Moderately Preterm Children Born at 32 to 36 Weeks’ Gestational Age. PEDIATRICS, 124, 251–257."

[["Chapter 14"]]
doi = "10.1542/peds.2010-1536"
number = "3b"
name = "Talge, N. M., Holzman, C., Wang, J., Lucia, V., Gardiner, J., & Breslau, N. (2010). Late-Preterm Birth and Its Association With Cognitive and Socioemotional Outcomes at 6 Years of Age. PEDIATRICS, 126, 1124–1131."

[["Chapter 14"]]
doi = "10.1002/14651858.CD004454.pub3"
number = 6
name = "Roberts, D., Brown, J., Medley, N., & Dalziel, S. R. (2017). Antenatal corticosteroids for accelerating fetal lung maturation for women at risk of preterm birth. Cochrane Database of Systematic Reviews. doi:10.1002/14651858.cd004454.pub3"

[["Chapter 14"]]
doi = "10.1002/14651858.CD003581.pub3"
number = 7
name = "Sosa, C. G., Althabe, F., Belizán, J. M., & Bergel, E. (2015). Bed rest in singleton pregnancies for preventing preterm birth. Cochrane Database of Systematic Reviews. doi:10.1002/14651858.cd003581.pub3"

[["Chapter 14"]]
doi = "10.1002/14651858.CD000110.pub2"
number = 8
name = "Crowther, C. A., & Han, S. (2010). Hospitalisation and bed rest for multiple pregnancy. Cochrane Database of Systematic Reviews. doi:10.1002/14651858.cd000110.pub2"

[["Chapter 14"]]
doi = "10.1002/msj.20243"
number = 9
name = "Bigelow, C., & Stone, J. (2011). Bed Rest in Pregnancy. Mount Sinai Journal of Medicine: A Journal of Translational and Personalized Medicine, 78, 291–302."

[["Chapter 14"]]
doi = "10.1586/eog.11.28"
number = 10
name = "Maloni, J. A. (2011). Lack of evidence for prescription of antepartum bed rest. Expert Review of Obstetrics & Gynecology, 6, 385–393."

[["Chapter 14"]]
doi = "10.1002/msj.20243"
number = 11
name = "Bigelow, C., & Stone, J. (2011). Bed Rest in Pregnancy. Mount Sinai Journal of Medicine: A Journal of Translational and Personalized Medicine, 78, 291–302."

[["Chapter 14"]]
doi = "10.1016/j.ajog.2008.08.007"
number = 12
name = "Fox, N. S., Gelber, S. E., Kalish, R. B., & Chasen, S. T. (2009). The recommendation for bed rest in the setting of arrested preterm labor and premature rupture of membranes. American Journal of Obstetrics and Gynecology, 200, 165.e1–165.e6."

[["Chapter 15"]]
doi = "10.1016/S0002-9378(96)80003-2"
number = "2a"
name = "Wing, D. A., Paul, R. H., & Millar, L. K. (1996). Management of the symptomatic placenta previa: A randomized, controlled trial of inpatient versus outpatient expectant management. American Journal of Obstetrics and Gynecology, 175, 806–811."

[["Chapter 15"]]
doi = "10.1016/S0002-9378(12)91835-9"
number = "2b"
name = "Mouer, J. R. (1994). Placenta previa: Antepartum conservative management, inpatient versus outpatient. American Journal of Obstetrics and Gynecology, 170, 1683–1686."

[["Chapter 15"]]
doi = "10.1016/S0002-9378(13)90444-0"
number = "2c"
name = "Droste, S., & Keil, K. (1994). Expectant management of placenta previa: Cost-benefit analysis of outpatient treatment. American Journal of Obstetrics and Gynecology, 170, 1254–1257."

[["Chapter 16"]]
doi = "10.1002/uog.913"
number = 4
name = "Ramanathan, G., Yu, C., Osei, E., & Nicolaides, K. H. (2003). Ultrasound examination at 37 weeks’ gestation in the prediction of pregnancy outcome: the value of cervical assessment. Ultrasound in Obstetrics and Gynecology, 22, 598–603."

[["Chapter 16"]]
doi = "10.1067/mob.2001.111248"
number = 6
name = "Iams, J. D., Goldenberg, R. L., Mercer, B. M., Moawad, A. H., Meis, P. J., Das, A. F., … Roberts, J. H. (2001). The Preterm Prediction Study: Can low-risk women destined for spontaneous preterm birth be identified? American Journal of Obstetrics and Gynecology, 184, 652–655."

[["Chapter 17"]]
doi = "10.1371/journal.pmed.1002494"
number = 1
name = "Keag, O. E., Norman, J. E., & Stock, S. J. (2018). Long-term risks and benefits associated with cesarean delivery for mother, baby, and subsequent pregnancies: Systematic review and meta-analysis. PLOS Medicine, 15, e1002494."

[["Chapter 17"]]
doi = "10.1016/j.clp.2011.03.008"
number = 2
name = "Neu, J., & Rushing, J. (2011). Cesarean Versus Vaginal Delivery: Long-term Infant Outcomes and the Hygiene Hypothesis. Clinics in Perinatology, 38, 321–331."

[["Chapter 17"]]
doi = "10.1002/14651858.CD004945.pub3"
number = 4
name = "Gülmezoglu, A. M., Crowther, C. A., Middleton, P., & Heatley, E. (2012). Induction of labour for improving birth outcomes for women at or beyond term. Cochrane Database of Systematic Reviews. doi:10.1002/14651858.cd004945.pub3"

[["Chapter 17"]]
doi = "10.1016/j.ajog.2017.12.016"
number = 5
name = "Grobman, W. (2018). LB01: A randomized trial of elective induction of labor at 39 weeks compared with expectant management of low-risk nulliparous women. American Journal of Obstetrics and Gynecology, 218, S601."

[["Chapter 17"]]
doi = "10.1002/14651858.CD003246.pub2"
number = 6
name = "Alfirevic, Z., Kelly, A. J., & Dowswell, T. (2009). Intravenous oxytocin alone for cervical ripening and induction of labour. Cochrane Database of Systematic Reviews. doi:10.1002/14651858.cd003246.pub2"

[["Chapter 17"]]
doi = "10.1002/14651858.CD003101.pub2"
number = 7
name = "Kelly, A. J., Malik, S., Smith, L., Kavanagh, J., & Thomas, J. (2009). Vaginal prostaglandin (PGE2 and PGF2a) for induction of labour at term. Cochrane Database of Systematic Reviews. doi:10.1002/14651858.cd003101.pub2"

[["Chapter 18"]]
doi = "10.1067/mob.2002.127142"
number = 2
name = "Zhang, J., Troendle, J. F., & Yancey, M. K. (2002). Reassessing the labor curve in nulliparous women. American Journal of Obstetrics and Gynecology, 187, 824–828."

[["Chapter 18"]]
doi = "10.1111/j.1471-0528.1985.tb01043.x"
number = 4
name = "WESTGREN, M., EDVALL, H., NORDSTRoM, L., SVALENIUS, E., & RANSTAM, J. (1985). Spontaneous cephalic version of breech presentation in the last trimester. BJOG: An International Journal of Obstetrics and Gynaecology, 92, 19–22."

[["Chapter 18"]]
doi = "10.1002/14651858.CD000083.pub3"
number = 5
name = "Hofmeyr, G. J., Kulier, R., & West, H. M. (2015). External cephalic version for breech presentation at term. Cochrane Database of Systematic Reviews. doi:10.1002/14651858.cd000083.pub3"

