[["Chapter 7"]]
doi = "10.1002/tera.1420500105"
number = 13
name = "McKeigue, P. M., Lamm, S. H., Linn, S., & Kutcher, J. S. (1994). Bendectin and birth defects: I. A meta-analysis of the epidemiologic studies. Teratology, 50, 27–37."

[["Chapter 8"]]
doi = "10.1146/annurev-med-091014-115715"
number = 3
name = "Wong, F. C. K., & Lo, Y. M. D. (2016). Prenatal Diagnosis Innovation: Genome Sequencing of Maternal Plasma. Annual Review of Medicine, 67, 419–432."

[["Chapter 8"]]
doi = "10.1016/S0140-6736(97)02449-5"
number = 10
name = "Sundberg, K., Bang, J., Smidt-Jensen, S., Brocks, V., Lundsteen, C., Parner, J., … Philip, J. (1997). Randomised study of risk of fetal loss related to early amniocentesis versus chorionic villus sampling. The Lancet, 350, 697–703."

[["Chapter 13"]]
doi = "10.1016/j.placenta.2005.09.001"
number = 1
name = "GEDEON, C., & KOREN, G. (2006). Designing Pregnancy Centered Medications: Drugs Which Do Not Cross the Human Placenta☆. Placenta, 27, 861–868."

